tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "surface-dim": "#131314",
                        "surface-container-lowest": "#0e0e0f",
                        "inverse-surface": "#e5e2e3",
                        "background": "#131314",
                        "on-primary-fixed-variant": "#3323cc",
                        "error-container": "#93000a",
                        "outline": "#918fa1",
                        "on-primary-fixed": "#0f0069",
                        "tertiary-fixed-dim": "#ffb695",
                        "primary-fixed": "#e2dfff",
                        "surface-tint": "#c3c0ff",
                        "on-error-container": "#ffdad6",
                        "on-secondary": "#00344d",
                        "surface-bright": "#3a393a",
                        "on-background": "#e5e2e3",
                        "on-primary": "#1d00a5",
                        "on-secondary-container": "#00344e",
                        "tertiary": "#ffb695",
                        "on-tertiary": "#571f00",
                        "on-tertiary-fixed": "#351000",
                        "surface-container-highest": "#353436",
                        "secondary-fixed-dim": "#89ceff",
                        "on-secondary-fixed-variant": "#004c6e",
                        "primary": "#c3c0ff",
                        "on-tertiary-container": "#ffd2be",
                        "surface-variant": "#353436",
                        "surface-container": "#201f20",
                        "outline-variant": "#464555",
                        "on-surface-variant": "#c7c4d8",
                        "tertiary-container": "#a44100",
                        "secondary": "#89ceff",
                        "inverse-primary": "#4d44e3",
                        "inverse-on-surface": "#313031",
                        "tertiary-fixed": "#ffdbcc",
                        "on-secondary-fixed": "#001e2f",
                        "surface-container-high": "#2a2a2b",
                        "secondary-fixed": "#c9e6ff",
                        "primary-fixed-dim": "#c3c0ff",
                        "primary-container": "#4f46e5",
                        "secondary-container": "#00a2e6",
                        "on-error": "#690005",
                        "on-tertiary-fixed-variant": "#7b2f00",
                        "on-surface": "#e5e2e3",
                        "surface-container-low": "#1c1b1c",
                        "on-primary-container": "#dad7ff",
                        "surface": "#131314",
                        "error": "#ffb4ab"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "xl": "48px",
                        "container-max": "1440px",
                        "unit": "4px",
                        "gutter": "16px",
                        "sm": "8px",
                        "lg": "24px",
                        "xs": "4px",
                        "sidebar-width": "240px",
                        "md": "16px"
                    },
                    "fontFamily": {
                        "body-lg": ["Inter"],
                        "body-md": ["Inter"],
                        "headline-lg": ["Inter"],
                        "headline-lg-mobile": ["Inter"],
                        "display": ["Inter"],
                        "headline-md": ["Inter"],
                        "label-md": ["Geist"],
                        "code-sm": ["jetbrainsMono"]
                    },
                    "fontSize": {
                        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                        "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600"}],
                        "headline-lg-mobile": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                        "display": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
                        "headline-md": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
                        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
                        "code-sm": ["12px", {"lineHeight": "18px", "fontWeight": "400"}]
                    }
                },
            },
        }
